/*
 * enclave_datawrite.cc — Trusted Container assembly & OCALL-based persistence
 */

#include "enclave_datawrite.h"
#include "Enclave_t.h"  /* generated by sgx_edger8r — provides ocall_write_container */

EnclaveDataWrite::EnclaveDataWrite()
    : curOffset_(0), containerNum_(0)
{
    curContainer_.size        = 0;
    curContainer_.containerID = 0;
    curContainer_.chunkNum    = 0;
    memset(storageKey_, 0, SGX_AES_GCM_KEY_SIZE);
}

EnclaveDataWrite::~EnclaveDataWrite() {}

void EnclaveDataWrite::SetStorageKey(const uint8_t key[SGX_AES_GCM_KEY_SIZE])
{
    memcpy(storageKey_, key, SGX_AES_GCM_KEY_SIZE);
}

/*
 * Flush the current container to untrusted storage via OCALL.
 * Before sending, we encrypt the entire container data with AES-GCM
 * and prepend the metadata header (size, IV, MAC) so that the
 * untrusted host can persist it opaquely.
 */
void EnclaveDataWrite::FlushContainer()
{
    if (curContainer_.size == 0)
        return;

    /*
     * Output layout for one container blob:
     *   [8 bytes: plaintext_size] [12 bytes: IV] [16 bytes: MAC] [ciphertext...]
     * Total = 36 + curContainer_.size
     */
    size_t header_len = sizeof(uint64_t) + SGX_AES_GCM_IV_SIZE + SGX_AES_GCM_MAC_SIZE;
    size_t total_len  = header_len + curContainer_.size;

    uint8_t* buf = (uint8_t*)malloc(total_len);
    if (!buf) return;

    /* Write plaintext size */
    memcpy(buf, &curContainer_.size, sizeof(uint64_t));

    uint8_t* iv_ptr  = buf + sizeof(uint64_t);
    uint8_t* mac_ptr = iv_ptr + SGX_AES_GCM_IV_SIZE;
    uint8_t* ct_ptr  = mac_ptr + SGX_AES_GCM_MAC_SIZE;

    /* Encrypt container data in-place into buf */
    enclave_aes_gcm_encrypt(
        storageKey_,
        curContainer_.data, curContainer_.size,
        iv_ptr, mac_ptr, ct_ptr);

    /* OCALL — untrusted host persists the encrypted blob */
    ocall_write_container(buf, total_len, curContainer_.containerID);

    free(buf);

    /* Reset container state for the next batch */
    containerNum_++;
    curOffset_               = 0;
    curContainer_.size       = 0;
    curContainer_.containerID = containerNum_;
    curContainer_.chunkNum   = 0;
}

/*
 * Insert a non-LZ4-compressed chunk (or a delta chunk).
 * chunk.chunkPtr holds the payload to store.
 */
bool EnclaveDataWrite::Chunk_Insert(TChunk_t& chunk)
{
    size_t tmpSize = (chunk.deltaFlag == SGX_NO_DELTA)
                         ? chunk.chunkSize
                         : chunk.saveSize;

    curContainer_.chunkNum++;

    /* Flush if adding this chunk would overflow the container */
    if (curContainer_.size + tmpSize > SGX_CONTAINER_MAX_SIZE) {
        FlushContainer();
    }

    /* Record where this chunk lands */
    chunk.containerID = containerNum_;
    chunk.offset      = curOffset_;

    memcpy(curContainer_.data + curOffset_, chunk.chunkPtr, tmpSize);
    curContainer_.size += tmpSize;
    curOffset_         += tmpSize;

    /* Transfer ownership: free the chunk buffer */
    free(chunk.chunkPtr);
    chunk.chunkPtr = nullptr;

    /* Persist metadata in memory */
    chunklist.push_back(chunk);

    return true;
}

/*
 * Insert an LZ4-compressed base chunk.
 * The compressed bytes are in lz4Buffer[0..chunk.saveSize).
 */
bool EnclaveDataWrite::Chunk_Insert(TChunk_t& chunk, uint8_t* lz4Buffer)
{
    size_t tmpSize = chunk.saveSize;

    curContainer_.chunkNum++;

    if (curContainer_.size + tmpSize > SGX_CONTAINER_MAX_SIZE) {
        FlushContainer();
    }

    chunk.containerID = containerNum_;
    chunk.offset      = curOffset_;

    memcpy(curContainer_.data + curOffset_, lz4Buffer, tmpSize);
    curContainer_.size += tmpSize;
    curOffset_         += tmpSize;

    free(chunk.chunkPtr);
    chunk.chunkPtr = nullptr;

    chunklist.push_back(chunk);

    return true;
}

void EnclaveDataWrite::ProcessLastContainer()
{
    FlushContainer();
}

/*
 * Get_Chunk_Info — retrieve a stored chunk's data from the in-memory
 * container that is still alive (since we are running one version at a time
 * and the whole dataset fits in Enclave memory for the prototype).
 *
 * For the SGX prototype we keep all chunk data in Enclave memory via
 * chunklist[].  In production you would add a trusted cache layer.
 */
TChunk_t EnclaveDataWrite::Get_Chunk_Info(int id)
{
    TChunk_t info = chunklist[id];
    /* Data must be re-loaded from Container — for simplicity in the
       prototype we keep a copy in Enclave memory (the Container itself
       is already in curContainer_.data if it hasn't been flushed, or
       we store a copy at insert time). */
    /* NOTE: The real chunk payload was freed after insert.
       For base-chunk lookups during delta compression, we need to
       keep the data.  We solve this by allocating a copy in Chunk_Insert
       for base chunks.  This is handled by the BiSearch logic
       which stores base data separately. */
    return info;
}

TChunk_t EnclaveDataWrite::Get_Chunk_MetaInfo(int id)
{
    /* Returns metadata only, chunkPtr is null. */
    TChunk_t info = chunklist[id];
    info.chunkPtr = nullptr;
    return info;
}

bool EnclaveDataWrite::Recipe_Insert(uint64_t chunkID)
{
    recipeMap_[filename_].push_back(chunkID);
    return true;
}

bool EnclaveDataWrite::Recipe_Header_Insert(uint64_t chunkID)
{
    recipeMapHeader_[filename_].push_back(chunkID);
    return true;
}

void EnclaveDataWrite::ClearAllCache()
{
    /* Nothing to clear in the prototype — containers are flushed via OCALL
       and chunks remain in chunklist for cross-version lookups. */
}
